embedding_size: 64
feat_embed_dim: 64
n_mm_layers: 1
n_layers: 2
knn_k: 10
mm_image_weight: 0.1
aggr_mode: "add"
learning_rate: 0.0001
weight_size: [64]
lambda_coeff: 0.9
lambda_spec: [0.1]
dct_keep_ratio: 0.2
beta_lf: 0.6
beta_hf: 0.2
beta_mix: 0.2
spec_gate_tau: 1
enable_spec_gate: False
enable_residual: False
decay_base: 0.9
decay_weight: [0.95]
weight_decay: [1e-4]
item_co_topk: 10
alpha_item_co: [0.2]
cui_topk: 10
cui_theta: 0.1
cui_gamma: [0.1] 
gpert_mask_p: 0.2

 # baby
n_ui_layers: 3
reg_weight: [0.001]
dropout: 0.1
clu_lambda: [1e-4]
cli_lambda: [1e-5]
gpert_lambda: [1e-4]

# # sports
# n_ui_layers: 4
# reg_weight: [0.01]
# dropout: 0.05
# clu_lambda: [1e-5]
# cli_lambda: [1e-4]
# gpert_lambda: [1e-2]

# clothing
#n_ui_layers: 3
#reg_weight: [0.001]
#dropout: 0.01
#clu_lambda: [1e-4]
#cli_lambda: [1e-5]
#gpert_lambda: [1e-1]



hyper_parameters:
  [
    "reg_weight",
    "weight_decay",
    "decay_weight",
    "alpha_item_co",
    "clu_lambda",
    "cli_lambda",
    "gpert_lambda",
    "lambda_spec",
    "cui_gamma",
  ]
